#ifndef BASE_DEFINES_INCLUDE_H
#define BASE_DEFINES_INCLUDE_H

//#define DEV_MODE
#define START_AT_TITLESCREEN
//#define DISABLE_ENEMIES



#ifdef _WIN32
#define _WINDOWS
#endif

#ifdef _WIN64
#define _WINDOWS
#endif

#define TARGET_FPS 60

#define FRAMEBUFFER_WIDTH  256
#define FRAMEBUFFER_HEIGHT 192
#define FRAMEBUFFER_PITCH  (FRAMEBUFFER_WIDTH / 8)
#define FRAMEBUFFER_SIZE_IN_BYTES   0x1800

#define GET_FRAMEBUFFER_LOCATION(x, y) (((x) >> 2) + ((y) << 5)) // FRAMEBUFFER_PITCH

#define NUM_ROOMS					10
#define NUM_ROOMS_PLUS_TITLESCREN	11
#define NUM_ROOMS_AND_ALL			14
#define TITLESCREEN_ROOM_INDEX		10	
#define TRANSITION_ROOM_INDEX		11
#define WIPE_TRANSITION_ROOM_INDEX	12
#define GET_READY_ROOM_INDEX		13

#define SCORE_DRAW_LOCATION			0x1703


#define SET_HIGH_BYTE(v) (v << 8)
#define GET_HIGH_BYTE(v) ((u8)((v) >> 8))
#define GET_LOW_BYTE(v) ((u8)v)

#endif