#ifndef BASE_DEFINES_INCLUDE_H
#define BASE_DEFINES_INCLUDE_H

#define FRAMEBUFFER_WIDTH  256
#define FRAMEBUFFER_HEIGHT 192
#define FRAMEBUFFER_PITCH  (FRAMEBUFFER_WIDTH / 8)
#define FRAMEBUFFER_SIZE_IN_BYTES   0x1800

#define NUM_ROOMS 12
#define TITLE_SCREEN_ROOM_INDEX 10
#define TRANSITION_ROOM_INDEX 11

#endif