#ifndef GBA_DEFINES_INCLUDE_H
#define GBA_DEFINES_INCLUDE_H

#define UI_BACKGROUND_INDEX			0
#define GAME_BACKGROUND_INDEX		1
#define TRANSITION_BACKGROUND_INDEX	2

#define TRANSITION_TILEMAP_INDEX	31
#define UI_TILEMAP_INDEX			30
#define GAME_TILEMAP_INDEX			29

#define TRANSITION_BACKGROUND_PRIORITY	0
#define UI_SPRITE_PRIORITY				0
#define UI_BACKGROUND_PRIORITY			1
#define SPRITE_PRIORITY					2
#define GAME_BACKGROUND_PRIORITY		3
#endif