#ifndef SATURN_INCLUDE_H
#define SATURN_INCLUDE_H

#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240
#define HALF_SCREEN_WIDTH (SCREEN_WIDTH / 2)
#define HALF_SCREEN_HEIGHT (SCREEN_HEIGHT / 2)

#define SCREEN_OFFSET_X ((SCREEN_WIDTH - 256) / 2)
#define SCREEN_OFFSET_Y ((SCREEN_HEIGHT - 192) / 2)

#endif