;this file for FamiTone2 library generated by text2data tool

LoopingEffects_music_data:
	.db 3
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256
	.dw .song1ch0,.song1ch1,.song1ch2,.song1ch3,.song1ch4,307,256
	.dw .song2ch0,.song2ch1,.song2ch2,.song2ch3,.song2ch4,307,256

.instruments:
	.db $30 ;instrument $00
	.dw .env1,.env0,.env3
	.db $00
	.db $30 ;instrument $01
	.dw .env1,.env2,.env3
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $cf,$cc,$c5,$c2,$c1,$c0,$00,$05
.env2:
	.db $b6,$b0,$af,$ae,$00,$03
.env3:
	.db $a7,$80,$80,$80,$00,$03


.song0ch0:
	.db $fb,$04
.song0ch0loop:
.ref0:
	.db $8f
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref1:
	.db $8f
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref2:
	.db $8f
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref3:
	.db $80,$04,$00,$83,$20,$00,$83
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref4:
	.db $8f
	.db $fd
	.dw .song0ch4loop


.song1ch0:
	.db $fb,$05
.song1ch0loop:
.ref5:
	.db $8f
	.db $fd
	.dw .song1ch0loop

.song1ch1:
.song1ch1loop:
.ref6:
	.db $80,$2c,$00,$30,$00,$2c,$00,$30,$00
	.db $fd
	.dw .song1ch1loop

.song1ch2:
.song1ch2loop:
.ref7:
	.db $8f
	.db $fd
	.dw .song1ch2loop

.song1ch3:
.song1ch3loop:
.ref8:
	.db $8f
	.db $fd
	.dw .song1ch3loop

.song1ch4:
.song1ch4loop:
.ref9:
	.db $8f
	.db $fd
	.dw .song1ch4loop


.song2ch0:
	.db $fb,$06
.song2ch0loop:
.ref10:
	.db $8f
	.db $fd
	.dw .song2ch0loop

.song2ch1:
.song2ch1loop:
.ref11:
	.db $80,$30,$00,$2c,$00,$30,$00,$2c,$00
	.db $fd
	.dw .song2ch1loop

.song2ch2:
.song2ch2loop:
.ref12:
	.db $8f
	.db $fd
	.dw .song2ch2loop

.song2ch3:
.song2ch3loop:
.ref13:
	.db $8f
	.db $fd
	.dw .song2ch3loop

.song2ch4:
.song2ch4loop:
.ref14:
	.db $8f
	.db $fd
	.dw .song2ch4loop
