;this file for FamiTone2 library generated by text2data tool

LoopingEffects_music_data:
	.byte 3
	.word .Linstruments
	.word .Lsamples-3
	.word .Lsong0ch0,.Lsong0ch1,.Lsong0ch2,.Lsong0ch3,.Lsong0ch4,307,256 ; run
	.word .Lsong1ch0,.Lsong1ch1,.Lsong1ch2,.Lsong1ch3,.Lsong1ch4,307,256 ; climb_up
	.word .Lsong2ch0,.Lsong2ch1,.Lsong2ch2,.Lsong2ch3,.Lsong2ch4,307,256 ; climb_down

.Linstruments:
	.byte $30 ;instrument $00
	.word .Lenv1,.Lenv0,.Lenv3
	.byte $00
	.byte $30 ;instrument $01
	.word .Lenv1,.Lenv2,.Lenv3
	.byte $00

.Lsamples:
.Lenv0:
	.byte $c0,$00,$00
.Lenv1:
	.byte $cf,$cc,$c5,$c2,$c1,$c0,$00,$05
.Lenv2:
	.byte $b6,$b0,$af,$ae,$00,$03
.Lenv3:
	.byte $a7,$80,$80,$80,$00,$03


; run
.Lsong0ch0:
	.byte $fb,$04
.Lsong0ch0loop:
.Lref0:
	.byte $8f
	.byte $fd
	.word .Lsong0ch0loop

; run
.Lsong0ch1:
.Lsong0ch1loop:
.Lref1:
	.byte $8f
	.byte $fd
	.word .Lsong0ch1loop

; run
.Lsong0ch2:
.Lsong0ch2loop:
.Lref2:
	.byte $8f
	.byte $fd
	.word .Lsong0ch2loop

; run
.Lsong0ch3:
.Lsong0ch3loop:
.Lref3:
	.byte $80,$04,$00,$83,$20,$00,$83
	.byte $fd
	.word .Lsong0ch3loop

; run
.Lsong0ch4:
.Lsong0ch4loop:
.Lref4:
	.byte $8f
	.byte $fd
	.word .Lsong0ch4loop


; climb_up
.Lsong1ch0:
	.byte $fb,$05
.Lsong1ch0loop:
.Lref5:
	.byte $8f
	.byte $fd
	.word .Lsong1ch0loop

; climb_up
.Lsong1ch1:
.Lsong1ch1loop:
.Lref6:
	.byte $80,$2c,$00,$30,$00,$2c,$00,$30,$00
	.byte $fd
	.word .Lsong1ch1loop

; climb_up
.Lsong1ch2:
.Lsong1ch2loop:
.Lref7:
	.byte $8f
	.byte $fd
	.word .Lsong1ch2loop

; climb_up
.Lsong1ch3:
.Lsong1ch3loop:
.Lref8:
	.byte $8f
	.byte $fd
	.word .Lsong1ch3loop

; climb_up
.Lsong1ch4:
.Lsong1ch4loop:
.Lref9:
	.byte $8f
	.byte $fd
	.word .Lsong1ch4loop


; climb_down
.Lsong2ch0:
	.byte $fb,$06
.Lsong2ch0loop:
.Lref10:
	.byte $8f
	.byte $fd
	.word .Lsong2ch0loop

; climb_down
.Lsong2ch1:
.Lsong2ch1loop:
.Lref11:
	.byte $80,$30,$00,$2c,$00,$30,$00,$2c,$00
	.byte $fd
	.word .Lsong2ch1loop

; climb_down
.Lsong2ch2:
.Lsong2ch2loop:
.Lref12:
	.byte $8f
	.byte $fd
	.word .Lsong2ch2loop

; climb_down
.Lsong2ch3:
.Lsong2ch3loop:
.Lref13:
	.byte $8f
	.byte $fd
	.word .Lsong2ch3loop

; climb_down
.Lsong2ch4:
.Lsong2ch4loop:
.Lref14:
	.byte $8f
	.byte $fd
	.word .Lsong2ch4loop
