#ifndef CHAMBERS_INCLUDE_H
#define CHAMBERS_INCLUDE_H

#include "../base_defines.h"

#define PLAYERLIVES_ICON_X	0x14
#define PLAYERLIVES_ICON_Y	0x2
#define PLAYERLIVES_ICON_SPACING 0xc // 0x3 bytes * 4 pixels
#define PLAYERICON_NUM_SPRITE_ROWS 7

#define PLAYERLIVES_DRAW_LOCATION  GET_FRAMEBUFFER_LOCATION(PLAYERLIVES_ICON_X, PLAYERLIVES_ICON_Y)
#define PLAYERLIVES_TEXT_DRAW_LOCATION  (PLAYERLIVES_DRAW_LOCATION - 0x4)
#define CHAMBER_TEXT_DRAW_LOCATION  0x55
#define CHAMBER_NUMBER_TEXT_DRAW_LOCATION  (CHAMBER_TEXT_DRAW_LOCATION + 8)
#define TIMER_DRAW_LOCATION 0x1716

#endif