#ifndef TITLE_SCREEN_INCLUDE_H
#define TITLE_SCREEN_INCLUDE_H

#define TITLESCREEN_HIGHSCORE_LOCATION			0x12cc
#define TITLESCREEN_PLAYERONE_SCORE_LOCATION	0x1412
#define TITLESCREEN_PLAYERTWO_SCORE_LOCATION	0x1552

#endif